# Phosh compositor (phoc) configuration for Samsung Galaxy S20 FE 5G (r8q).
# Physical panel: 6.5" 1080x2400 120Hz Super AMOLED.

#[core]
#xwayland=false

[output:DSI-1]
scale = 2

[output:Virtual-1]
# x86 VM (QXL) output for testing in qemu.
modeline = 138.50  1920 1968 2000 2080  1200 1203 1209 1235 +hsync -vsync
mode = 1920x1200
scale = 1

[output:X11-1]
mode = 1400x900
scale = 1

[output:WL-1]
mode = 1400x900
scale = 1

[output:HWCOMPOSER-1]
# 1080x2400 / 2 = 540x1200 logical resolution.
scale = 2
